# Generated by Django 5.2.6 on 2025-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('En mantenimiento', 'En mantenimiento')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
