# Generated by Django 5.2.6 on 2025-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcategory_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
