# Generated by Django 5.2.6 on 2025-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('En mantenimiento', 'En mantenimiento')], default='Disponible', max_length=20),
        ),
    ]
